language: node_js
node_js:
- node
deploy:
  provider: npm
  email: cosmoserdean@gmail.com
  api_key:
    secure: DqfveIibs5QDF3g6JLMfJZMSp9o8GcpUC7DzCILQku3WSFzv0+DPxCEBczRL4Z50uH4M/h1HcF/GQXMlGcQahr3AZG87z8SzoAJK+evHW0SwqDZFlrOrtq349jseJ4RNevhVTZM9AB75bGc+P4nR4iYfzHJaFUHCLEEJIZK+7PBjnhrVU58jCpuGiOURquoYXL7rWoIc6KSvTnX718pV4F8kX8kg1QZwpPP4Jz/YMHMwO2fnfUeOEifQjIH4MOId5ASQYIg7uR4eV9KTzTBNlu/2jz2J3vNCUMoLwMeS8mltzwFAYv+OipYgvQdzfxJOFG0mMJ0AINbUK97saqpjU8RUezR8H3kXPDhrw+nqUXzVoH87okcntJwsCH+/hD95dgsj7NiM6sAlwBGyrCkBSYjrk1P9M1WKFKnAVz/9jKOo6ZDto+J2bxQf4R8ifDye+OEzn6Cc7x/lRJ0Nc5LAvuRcgGTysLtlT/92ZEfWuX5EX0KmDiyzhFGrppk0kL8UWx9cIUlKqo2hIvL0lFEnxq2uxwbhVZAip0p2dFhskiKgyDyKSLXukJsafyuyNs3A+3kRonDBVhtGcm86bx5qkXUstuJR1Se53PYoizo2I8YswUJ7gOaw/JjoSk9M8XJwYjTZ0lSVkN4l2Z89dMwD0NMyn074zQJ6sE1+/ONfOoA=
